spring:
  application:
    name: trip-service
  datasource:
    url: jdbc:postgresql://localhost:5555/fleetTrips
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
fleet-management:
  config:
    kafka:
      server-url: "http://localhost:29092"
      topics:
        trip-started: "fleet.trip.started"
        trip-ended: "fleet.trip.ended"

  trip-service:
    clients:
      drivers:
        url: http://localhost:8081/fleet/management/api/drivers
      vehicles:
        url: http://localhost:8082/fleet/management/api/vehicles
server:
  port: 8083