spring:
  application:
    name: driver-service
  kafka:
    bootstrap-servers: "http://localhost:29092"
    consumer:
      group-id: fleet.tripstarted.to.driver
      auto-offset-reset: earliest

  datasource:
    url: jdbc:postgresql://localhost:5555/fleetDrivers
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
fleet-management:
  config:
    kafka:
      topics:
        trip-started: "fleet.trip.started"
        trip-ended: "fleet.trip.ended"
server:
  port: 8081
